import { Stack } from "@mui/material";
import Head from "next/head";
const Home = () => {
  return (
    <>
      <Head>
        <title>Food delivery</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/logo.svg" />
      </Head>
      <main>
        <Stack>
      
        </Stack>
      </main>
    </>
  );
};
export default Home;
