

import Header from "@/components/Header";
import { Box } from "@mui/material";
import Head from "next/head";
const Home=()=> {
  return (
    <>
      <Head>
        <title>Food delivery</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/logo.svg" />
      </Head>
      <main>
        <Box>
          <Header/>
        </Box>
      </main>
    </>
  );
}
export default Home