export const Home2 = [
    {
      category:"Хямдралтай",
      title: "Өглөөний цай",
      image: "/breakfast1.png",
      price: 16800,
      discount:14800,
      
    },
    {
      category:"Хямдралтай",
      title: "Зайрмаг",
      image: "/icecream.png",
      price: 6800,
      discount: 4800,
    },
    {
      category:"Хямдралтай",
      title: "Өглөөний цай",
      image: "/breakfast.png",
      price: 26800,
      discount: 24800,
    },
    {
      category:"Хямдралтай",
      title: "Breakfast",
      image: "/Өглөөний хоол.png",
      price: 26800,
      discount: 24800,
    },
    {
      category:"Үндсэн хоол",
      title: "Main Pizza ",
      image: "",
      price: 34800,
    },
    {
      category:"Үндсэн хоол",
      title: "Food tart",
      image: "",
      price: 22800,
    },
    {
      category:"Үндсэн хоол",
      title: "Өглөөний хоол",
      image: "",
      price: 14800,
    },
    {
      category:"Үндсэн хоол",
      title: "Зутан шөл",
      image: "",
      price: 17800,
    },
    {
      category:"Салад ба зууш",
      title: "Чихэрлэг тахиа",
      image: "",
      price: 24800,
    },
    {
      category:"Салад ба зууш",
      title: "Lunch",
      image: "",
      price: 24800,
    },
    {
      category:"Салад ба зууш",
      title: "Сэндвич",
      image: "",
      price: 14800,
    },
    {
      category:"Салад ба зууш",
      title: "Apple pie",
      image: "",
      price: 34800,
    },
    {
      category:"Амттан",
      title: "Торт",
      image: "",
      price: 54800,
    },
    {
      category:"Амттан",
      title: "Oreo shake",
      image: "",
      price: 14800,
    },
    {
      category:"Амттан",
      title: "Chocolate ",
      image: "",
      price: 14800,
    },
    {
      category:"Амттан",
      title: "Yoghurt",
      image: "",
      price: 14800,
    },
  ];