export const Home2 = [
  {
    id:1,
    category: "breakfast",
    title: "Өглөөний хоол",
    image: "/breakfast1.png",
    price: 16800,
    discount: 10,
    ingredients: ["Dough", "Tomato Sauce", "Cheese", "Toppings of choice"],
    stock: 30,
  },
  { 
    id:2,
    category: "breakfast",
    title: "Зайрмаг",
    image: "/icecream.png",
    price: 6800,
    discount: 20,
    ingredients: ["Dough", "Tomato Sauce", "Cheese", "Toppings of choice"],
    stock: 30,
  },
  {
    id:3,
    category: "breakfast",
    title: "Өглөөний хоол",
    image: "/breakfast.png",
    price: 26800,
    discount: 15,
    ingredients: ["Dough", "Tomato Sauce", "Cheese", "Toppings of choice"],
    stock: 30,
  },
  {
    id:4,
    category: "breakfast",
    title: "Breakfast",
    image: "/Өглөөний хоол.png",
    price: 26800,
    discount: 20,
    ingredients: ["Dough", "Tomato Sauce", "Cheese", "Toppings of choice"],
    stock: 30,
  },
  {
    id:5,
    category: "Maindish",
    title: "Main Pizza ",
    image: "/mainFood/MainPizza.png",
    price: 34800,
    discount: 0,
    ingredients: ["Dough", "Tomato Sauce", "Cheese", "Toppings of choice"],
    stock: 30,
  },
  {
    id:6,
    category: "Maindish",
    title: "Food tart",
    image: "/mainFood/FoodTart.png",
    price: 22800,
    discount: 0,
    ingredients: ["Dough", "Tomato Sauce", "Cheese", "Toppings of choice"],
    stock: 30,
  },
  {
    
    id:7,
    category: "Maindish",
    title: "Өглөөний хоол",
    image: "/mainFood/MorningBf.png",
    price: 14800,
    discount: 0,
    ingredients: ["Dough", "Tomato Sauce", "Cheese", "Toppings of choice"],
    stock: 30,
  },
  {
    id:8,
    category: "Maindish",
    title: "Зутан шөл",
    image: "/mainFood/Soup.png",
    price: 17800,
    discount: 0,
    ingredients: ["Dough", "Tomato Sauce", "Cheese", "Toppings of choice"],
    stock: 30,
  },
  {
    id:9,
    category: "Sidedish",
    title: "Чихэрлэг тахиа",
    image: "/sideDish/chicken.png",
    price: 24800,
    discount: 0,
    ingredients: ["Dough", "Tomato Sauce", "Cheese", "Toppings of choice"],
    stock: 30,
  },
  {
    id:10,
    category: "Sidedish",
    title: "Lunch",
    image: "/sideDish/Lunch.png",
    price: 24800,
    discount: 0,
    ingredients: ["Dough", "Tomato Sauce", "Cheese", "Toppings of choice"],
    stock: 30,
  },
  {id:11,
    category: "Sidedish",
    title: "Сэндвич",
    image: "/sideDish/sandwich.png",
    price: 14800,
    discount: 0,
    ingredients: ["Dough", "Tomato Sauce", "Cheese", "Toppings of choice"],
    stock: 30,
  },
  { id:12,
    category: "Sidedish",
    title: "Apple pie",
    image: "/sideDish/applePie.png",
    price: 34800,
    discount: 0,
    ingredients: ["Dough", "Tomato Sauce", "Cheese", "Toppings of choice"],
    stock: 30,
  },
  { id:13,
    category: "desert",
    title: "Торт",
    image: "/dessert/cake.png",
    price: 54800,
    discount: 0,
    ingredients: ["Dough", "Tomato Sauce", "Cheese", "Toppings of choice"],
    stock: 30,
  },
  { id:14,
    category: "desert",
    title: "Oreo shake",
    image: "/dessert/oreoCake.png",
    price: 14800,
    discount: 0,
    ingredients: ["Dough", "Tomato Sauce", "Cheese", "Toppings of choice"],
    stock: 30,
  },
  { id:15,
    category: "desert",
    title: "Chocolate ",
    image: "/dessert/chocolate.png",
    price: 14800,
    discount: 0,
    ingredients: ["Dough", "Tomato Sauce", "Cheese", "Toppings of choice"],
    stock: 30,
  },
  {
    id:16,
    category: "desert",
    title: "Yoghurt",
    image: "/dessert/yoghurt.png",
    price: 14800,
    discount: 0,
    ingredients: ["Dough", "Tomato Sauce", "Cheese", "Toppings of choice"],
    stock: 30,
  },
  {
    id:17,
    category: "breakfast",
    title: "Өглөөний хоол",
    image: "/breakfast1.png",
    price: 16800,
    discount: 10,
    ingredients: ["Dough", "Tomato Sauce", "Cheese", "Toppings of choice"],
    stock: 30,
  },
  { 
    id:18,
    category: "breakfast",
    title: "Зайрмаг",
    image: "/icecream.png",
    price: 6800,
    discount: 20,
    ingredients: ["Dough", "Tomato Sauce", "Cheese", "Toppings of choice"],
    stock: 30,
  },
  {
    id:19,
    category: "breakfast",
    title: "Өглөөний хоол",
    image: "/breakfast.png",
    price: 26800,
    discount: 15,
    ingredients: ["Dough", "Tomato Sauce", "Cheese", "Toppings of choice"],
    stock: 30,
  },
  {
    id:20,
    category: "breakfast",
    title: "Breakfast",
    image: "/Өглөөний хоол.png",
    price: 26800,
    discount: 20,
    ingredients: ["Dough", "Tomato Sauce", "Cheese", "Toppings of choice"],
    stock: 30,
  },
  {
    id:21,
    category: "Maindish",
    title: "Main Pizza ",
    image: "/mainFood/MainPizza.png",
    price: 34800,
    discount: 0,
    ingredients: ["Dough", "Tomato Sauce", "Cheese", "Toppings of choice"],
    stock: 30,
  },
  {
    id:22,
    category: "Maindish",
    title: "Food tart",
    image: "/mainFood/FoodTart.png",
    price: 22800,
    discount: 0,
    ingredients: ["Dough", "Tomato Sauce", "Cheese", "Toppings of choice"],
    stock: 30,
  },
  {
    
    id:23,
    category: "Maindish",
    title: "Өглөөний хоол",
    image: "/mainFood/MorningBf.png",
    price: 14800,
    discount: 0,
    ingredients: ["Dough", "Tomato Sauce", "Cheese", "Toppings of choice"],
    stock: 30,
  },
  {
    id:24,
    category: "Maindish",
    title: "Зутан шөл",
    image: "/mainFood/Soup.png",
    price: 17800,
    discount: 0,
    ingredients: ["Dough", "Tomato Sauce", "Cheese", "Toppings of choice"],
    stock: 30,
  },
  {
    id:25,
    category: "Sidedish",
    title: "Чихэрлэг тахиа",
    image: "/sideDish/chicken.png",
    price: 24800,
    discount: 0,
    ingredients: ["Dough", "Tomato Sauce", "Cheese", "Toppings of choice"],
    stock: 30,
  },
  {
    id:26,
    category: "Sidedish",
    title: "Lunch",
    image: "/sideDish/Lunch.png",
    price: 24800,
    discount: 0,
    ingredients: ["Dough", "Tomato Sauce", "Cheese", "Toppings of choice"],
    stock: 30,
  },
  {id:27,
    category: "Sidedish",
    title: "Сэндвич",
    image: "/sideDish/sandwich.png",
    price: 14800,
    discount: 0,
    ingredients: ["Dough", "Tomato Sauce", "Cheese", "Toppings of choice"],
    stock: 30,
  },
  { id:28,
    category: "Sidedish",
    title: "Apple pie",
    image: "/sideDish/applePie.png",
    price: 34800,
    discount: 0,
    ingredients: ["Dough", "Tomato Sauce", "Cheese", "Toppings of choice"],
    stock: 30,
  },
  { id:29,
    category: "desert",
    title: "Торт",
    image: "/dessert/cake.png",
    price: 54800,
    discount: 0,
    ingredients: ["Dough", "Tomato Sauce", "Cheese", "Toppings of choice"],
    stock: 30,
  },
  { id:30,
    category: "desert",
    title: "Oreo shake",
    image: "/dessert/oreoCake.png",
    price: 14800,
    discount: 0,
    ingredients: ["Dough", "Tomato Sauce", "Cheese", "Toppings of choice"],
    stock: 30,
  },
  { id:31,
    category: "desert",
    title: "Chocolate ",
    image: "/dessert/chocolate.png",
    price: 14800,
    discount: 0,
    ingredients: ["Dough", "Tomato Sauce", "Cheese", "Toppings of choice"],
    stock: 30,
  },
  {
    id:32,
    category: "desert",
    title: "Yoghurt",
    image: "/dessert/yoghurt.png",
    price: 14800,
    discount: 0,
    ingredients: ["Dough", "Tomato Sauce", "Cheese", "Toppings of choice"],
    stock: 30,
  },
];
