export const Home2 = [
  {
    category: "breakfast",
    title: "Өглөөний хоол",
    image: "/breakfast1.png",
    price: 16800,
    discount: 10,
  },
  {
    category: "breakfast",
    title: "Зайрмаг",
    image: "/icecream.png",
    price: 6800,
    discount: 20,
  },
  {
    category: "breakfast",
    title: "Өглөөний хоол",
    image: "/breakfast.png",
    price: 26800,
    discount: 15,
  },
  {
    category: "breakfast",
    title: "Breakfast",
    image: "/Өглөөний хоол.png",
    price: 26800,
    discount: 20,
  },
  {
    category: "Maindish",
    title: "Main Pizza ",
    image: "/mainFood/MainPizza.png",
    price: 34800,
    discount: 0,
  },
  {
    category: "Maindish",
    title: "Food tart",
    image: "/mainFood/FoodTart.png",
    price: 22800,
    discount: 0,
  },
  {
    category: "Maindish",
    title: "Өглөөний хоол",
    image: "/mainFood/MorningBf.png",
    price: 14800,
    discount: 0,
  },
  {
    category: "Maindish",
    title: "Зутан шөл",
    image: "/mainFood/Soup.png",
    price: 17800,
    discount: 0,
  },
  {
    category: "Sidedish",
    title: "Чихэрлэг тахиа",
    image: "",
    price: 24800,
    discount: 0,
  },
  {
    category: "Sidedish",
    title: "Lunch",
    image: "",
    price: 24800,
    discount: 0,
  },
  {
    category: "Sidedish",
    title: "Сэндвич",
    image: "",
    price: 14800,
    discount: 0,
  },
  {
    category: "Sidedish",
    title: "Apple pie",
    image: "",
    price: 34800,
    discount: 0,
  },
  {
    category: "desert",
    title: "Торт",
    image: "",
    price: 54800,
    discount: 0,
  },
  {
    category: "desert",
    title: "Oreo shake",
    image: "",
    price: 14800,
    discount: 0,
  },
  {
    category: "desert",
    title: "Chocolate ",
    image: "",
    price: 14800,
    discount: 0,
  },
  {
    category: "desert",
    title: "Yoghurt",
    image: "",
    price: 14800,
    discount: 0,
  },
];
